name: Process User List

on:
  push:
    branches:
      - main

jobs:
  process_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run script with environment variable input
      run: python test_list.py
      env:
        INPUT_STRING: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"