name: Check List Input

on:
  workflow_dispatch:
    inputs:
      list:
        description: 'Enter elements of a list separated by space :'
        required: true
        default: '1 2 3 4 5 6 7 8 90 89'
        type: string

jobs:
  process_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run pytest with default input list
      run: pytest -s --verbose
      env:
        INPUT_STRING: "${{ github.event.inputs.list }}"